### ISSUE TITLE
"this declaration has no storage type of class specifier" 

### ISSUE THREAD

**Issue by amycarleton** [friedmud/variadic_table#13]
When I copy the example exactly from the src file I get the above error.

```
#include "VariadicTable.h"

VariadicTable<std::string, double, int, std::string> vt({ "Name", "Weight", "Age", "Brother" });

vt.addRow({ "Cody", 180.2, 40, "John" });
vt.addRow({ "David", 175.3, 38, "Andrew" });
vt.addRow({ "Robert", 140.3, 27, "Fande" });

vt.print();
```

In my project, I get an error that says "too many initializer values". Different errors, but probably related to the same issue with the code. Anyone know why this might be? Specifically why the example code does not compile.

**Comment by Nilusche** [comment]
I had the same problem.
I found a way so that the code compiles and prints the right output.

```C++
VariadicTable<std::string, double, int, std::string> vt({ "Name", "Weight", "Age", "Brother" });

	vt.addRow("Cody", 180.2, 40, "John");
	vt.addRow("David", 175.3, 38, "Andrew");
	vt.addRow("Robert", 140.3, 27, "Fande");

	vt.print(std::cout);
```

**Comment by friedmud** [comment]
Good point... this changed along the way because I needed to be able to specify the stream.  I'll update the docs.
