### ISSUE TITLE
Compile error compiling main.c

### ISSUE THREAD

**Issue by digeye** [friedmud/variadic_table#3]
make all 
Building file: ../src/main.C
Invoking: GCC C++ Compiler
g++ -O0 -g3 -Wall -c -fmessage-length=0 -std=c++11 -MMD -MP -MF"src/main.d" -MT"src/main.o" -o "src/main.o" "../src/main.C"
../src/main.C: In function ‘int main()’:
../src/main.C:11:42: error: converting to ‘std::tuple<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {const char (&)[5], double, int, const char (&)[5]}; <template-parameter-2-2> = void; _Elements = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, int, std::basic_string<char, std::char_traits<char>, std::allocator<char> >}]’
     vt.addRow({"Cody", 180.2, 40, "John"});
                                          ^
../src/main.C:12:45: error: converting to ‘std::tuple<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {const char (&)[6], double, int, const char (&)[7]}; <template-parameter-2-2> = void; _Elements = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, int, std::basic_string<char, std::char_traits<char>, std::allocator<char> >}]’
     vt.addRow({"David", 175.3, 38, "Andrew"});
                                             ^
../src/main.C:13:45: error: converting to ‘std::tuple<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {const char (&)[7], double, int, const char (&)[6]}; <template-parameter-2-2> = void; _Elements = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, int, std::basic_string<char, std::char_traits<char>, std::allocator<char> >}]’
     vt.addRow({"Robert", 140.3, 27, "Fande"});
                                             ^
make: *** [src/main.o] Error 1

**Comment by chorfa007** [comment]
Hello,

I got a build error with g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39). Below compile errors:
g++ -c -std=c++11  -g -fno-omit-frame-pointer -O3 -MMD -MP -MF src/main-opt.o.d  -Iinclude -MT src/main-opt.o src/main.C -o src/main-opt.o 
src/main.C: In function \u2018int main()\u2019:
src/main.C:11:42: error: no matching function for call to \u2018VariadicTable<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::addRow(<brace-enclosed initializer list>)\u2019
     vt.addRow({"Cody", 180.2, 40, "John"});
                                          ^
src/main.C:11:42: note: candidate is:
In file included from src/main.C:1:0:
include/VariadicTable.h:75:8: note: void VariadicTable<Ts>::addRow(Ts ...) [with Ts = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, int, std::basic_string<char, std::char_traits<char>, std::allocator<char> >}]
   void addRow(Ts... entries) { _data.emplace_back(std::make_tuple(entries...)); }
        ^
include/VariadicTable.h:75:8: note:   candidate expects 4 arguments, 1 provided
src/main.C:12:45: error: no matching function for call to \u2018VariadicTable<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::addRow(<brace-enclosed initializer list>)\u2019
     vt.addRow({"David", 175.3, 38, "Andrew"});
                                             ^
src/main.C:12:45: note: candidate is:
In file included from src/main.C:1:0:
include/VariadicTable.h:75:8: note: void VariadicTable<Ts>::addRow(Ts ...) [with Ts = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, int, std::basic_string<char, std::char_traits<char>, std::allocator<char> >}]
   void addRow(Ts... entries) { _data.emplace_back(std::make_tuple(entries...)); }
        ^
include/VariadicTable.h:75:8: note:   candidate expects 4 arguments, 1 provided
src/main.C:13:45: error: no matching function for call to \u2018VariadicTable<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::addRow(<brace-enclosed initializer list>)\u2019
     vt.addRow({"Robert", 140.3, 27, "Fande"});
                                             ^
src/main.C:13:45: note: candidate is:
In file included from src/main.C:1:0:
include/VariadicTable.h:75:8: note: void VariadicTable<Ts>::addRow(Ts ...) [with Ts = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, int, std::basic_string<char, std::char_traits<char>, std::allocator<char> >}]
   void addRow(Ts... entries) { _data.emplace_back(std::make_tuple(entries...)); }
        ^
include/VariadicTable.h:75:8: note:   candidate expects 4 arguments, 1 provided
make: *** [src/main-opt.o] Error 1
