### ISSUE TITLE
Documentation is wrong - examples cause compile errors

### ISSUE THREAD

**Issue by monk-e-boy** [friedmud/variadic_table#7]
For people like me who copy the example and expect it to work, use this instead:
 
  VariadicTable<std::string, double, int, std::string> vt({"Name", "Weight", "Age", "Brother"});

  vt.addRow("Cody", 180.2, 40, "John");
  vt.addRow("David", 175.3, 38, "Andrew");
  vt.addRow("Robert", 140.3, 27, "Fande");

  vt.print(cout);

Also, the example code from the comments in the .h file are wrong:
 //VariadicTable<std::string, double, int, std::string> vt("Name", "Weight", "Age", "Brother");
this does not work.

**Comment by friedmud** [comment]
Thanks - sorry.  Updated the table from another project where I was using it and never updated anything else.
