### ISSUE TITLE
Table broken

### ISSUE THREAD

**Issue by monk-e-boy** [friedmud/variadic_table#9]
VariadicTable<std::string, int, double> vt({"Info", "#", "%"});

    vt.addRow("Rounds", stats.rounds, 0);
    vt.addRow("Doubles", stats.doubles, 98.333333);

    vt.print(os);

----------------------
|  Info   |   #  | % |
----------------------
| Rounds  | 5000 | 0 |
| Doubles | 4949 | 98.3333 |
----------------------

**Comment by friedmud** [comment]
Fixed - see current docs
